# Generated by Django 3.0.7 on 2020-11-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201112_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimano',
            name='ano',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='dimdia',
            name='dia',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='dimmes',
            name='nr_mes',
            field=models.IntegerField(unique=True),
        ),
    ]
