# Generated by Django 3.0.7 on 2020-11-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201113_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleversao',
            name='fato_versao',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='dimmes',
            name='nr_mes',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
