# Generated by Django 3.0.7 on 2020-11-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201113_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimmes',
            name='nr_mes',
            field=models.IntegerField(unique=True),
        ),
    ]
