# Generated by Django 3.0.7 on 2020-11-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201113_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimmes',
            name='nm_nr_mes',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
